//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionis.Resources.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursosNotas___Copia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursosNotas___Copia() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestionis.Resources.Idiomas.StringRecursosNotas - Copia", typeof(StringRecursosNotas___Copia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string btnFiltrar {
            get {
                return ResourceManager.GetString("btnFiltrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Nota.
        /// </summary>
        internal static string btnNuevaNota {
            get {
                return ResourceManager.GetString("btnNuevaNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar.
        /// </summary>
        internal static string btnRestaurarFiltro {
            get {
                return ResourceManager.GetString("btnRestaurarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Por:.
        /// </summary>
        internal static string lblFiltrarPor {
            get {
                return ResourceManager.GetString("lblFiltrarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALES.
        /// </summary>
        internal static string lblNDTotales {
            get {
                return ResourceManager.GetString("lblNDTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas del día.
        /// </summary>
        internal static string lblNotasDia {
            get {
                return ResourceManager.GetString("lblNotasDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas:.
        /// </summary>
        internal static string lblNotasTotales {
            get {
                return ResourceManager.GetString("lblNotasTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALES.
        /// </summary>
        internal static string lblNotasTotalesCount {
            get {
                return ResourceManager.GetString("lblNotasTotalesCount", resourceCulture);
            }
        }
    }
}
