//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionis.Resources.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursosAhorros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursosAhorros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestionis.Resources.Idiomas.StringRecursosAhorros", typeof(StringRecursosAhorros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string btnPersonalizado {
            get {
                return ResourceManager.GetString("btnPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20% para el ahorro:.
        /// </summary>
        internal static string lbl20PorCiento {
            get {
                return ResourceManager.GetString("lbl20PorCiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30% para gastos prescindibles:.
        /// </summary>
        internal static string lbl30PorCiento {
            get {
                return ResourceManager.GetString("lbl30PorCiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 50% para necesidades básicas:.
        /// </summary>
        internal static string lbl50PorCiento {
            get {
                return ResourceManager.GetString("lbl50PorCiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero disponible para ahorrar este mes:.
        /// </summary>
        internal static string lblDineroAhorrar {
            get {
                return ResourceManager.GetString("lblDineroAhorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero restante:.
        /// </summary>
        internal static string lblDineroRestante {
            get {
                return ResourceManager.GetString("lblDineroRestante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastado este mes:.
        /// </summary>
        internal static string lblGastadoMes {
            get {
                return ResourceManager.GetString("lblGastadoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastado este mes:.
        /// </summary>
        internal static string lblGastadoMes2 {
            get {
                return ResourceManager.GetString("lblGastadoMes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos fijos:.
        /// </summary>
        internal static string lblGastosFijos {
            get {
                return ResourceManager.GetString("lblGastosFijos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos variables:.
        /// </summary>
        internal static string lblGastosVariables {
            get {
                return ResourceManager.GetString("lblGastosVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se consideran gastos de necesidades básicas las categorias Luz y Supermercado.
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las demás categorías son consideradas como gastos prescindibles.
        /// </summary>
        internal static string lblInfo2 {
            get {
                return ResourceManager.GetString("lblInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos mensuales:.
        /// </summary>
        internal static string lblIngresosMes {
            get {
                return ResourceManager.GetString("lblIngresosMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentajes.
        /// </summary>
        internal static string lblPorcentajes {
            get {
                return ResourceManager.GetString("lblPorcentajes", resourceCulture);
            }
        }
    }
}
