//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionis.Resources.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursosGestor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursosGestor() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestionis.Resources.Idiomas.StringRecursosGestor", typeof(StringRecursosGestor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir deuda.
        /// </summary>
        internal static string btnAnyadirDeuda {
            get {
                return ResourceManager.GetString("btnAnyadirDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Deuda.
        /// </summary>
        internal static string btnEliminarDeuda {
            get {
                return ResourceManager.GetString("btnEliminarDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Todo.
        /// </summary>
        internal static string btnRestaurar {
            get {
                return ResourceManager.GetString("btnRestaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debo.
        /// </summary>
        internal static string chkDebo {
            get {
                return ResourceManager.GetString("chkDebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debo.
        /// </summary>
        internal static string lblDeboBarra {
            get {
                return ResourceManager.GetString("lblDeboBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deudas totales:.
        /// </summary>
        internal static string lblDeudasTotales {
            get {
                return ResourceManager.GetString("lblDeudasTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deudas totales:.
        /// </summary>
        internal static string lblDeudasTotalesValor {
            get {
                return ResourceManager.GetString("lblDeudasTotalesValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha límite:.
        /// </summary>
        internal static string lblFechaLimite {
            get {
                return ResourceManager.GetString("lblFechaLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblFechaLimiteValor {
            get {
                return ResourceManager.GetString("lblFechaLimiteValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Me deben.
        /// </summary>
        internal static string lblMeDeben {
            get {
                return ResourceManager.GetString("lblMeDeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Próxima deuda:.
        /// </summary>
        internal static string lblProximaDeuda {
            get {
                return ResourceManager.GetString("lblProximaDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblProximaDeudaValor {
            get {
                return ResourceManager.GetString("lblProximaDeudaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUMEN TOTAL.
        /// </summary>
        internal static string lblResumen {
            get {
                return ResourceManager.GetString("lblResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo:.
        /// </summary>
        internal static string lblSaldo {
            get {
                return ResourceManager.GetString("lblSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblTipo {
            get {
                return ResourceManager.GetString("lblTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblTipoValor {
            get {
                return ResourceManager.GetString("lblTipoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el título:.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
    }
}
